### ISSUE TITLE
The message after activating the reconciliation service in the terminal from csv-reconcile has incorrect service url.

### ISSUE THREAD

**Issue by ayushrai206** [gitonthescene/csv-reconcile#113]
While trying to run a reconciliation service with the help of csv-reconcile reconciliation service from a csv file in the terminal, it leads us to the message ->"Running on http://127.0.0.1:5000/". The url"http://127.0.0.1:5000/" gives an error message when we click it or when we try adding it in OpenRefine as a service, while the actual service url is given in the instructions of the csv-reconcile website.When we click on the actual service url it leads us to the Service manifest and it is also successfully added as a service in OpenRefine.
The url in the message should essentially redirect to the service url (which is http://127.0.0.1:5000/reconcile)which would be very convenient for the users

**Comment by gitonthescene** [comment]
I'm not 100% where you're seeing the url that you're clicking on.  Didn't you have to type it in?  The message mentioning http://127.0.0.1:5000 comes from the underlying Flask http server but the API point for the reconciliation service is http://127.0.0.1:5000/reconcile which as you say is mentioned on the README.

I hope this clears things up.

Regards,
-Doug
