### ISSUE TITLE
Problem with CSV dialect sniffing

### ISSUE THREAD

**Issue by b2m** [gitonthescene/csv-reconcile#68]
I tested the new behaviour for CSV dialect sniffing introduced for #41 in #42 and discovered the following problems:

1. The [csv.Sniffer().sniff()](https://docs.python.org/3/library/csv.html#csv.Sniffer.sniff) method will throw a "Could not determine delimiter" error in case it is unsure about a delimiter. 
2. I can not overwrite this behaviour via the `CSVKWARGS` configuration because it is applied later.

https://github.com/gitonthescene/csv-reconcile/blob/bc723c711232b523d5f0598a39a911ed0619fa35/csv_reconcile/initdb.py#L76

The reason for `csv.Sniffer()` being unsure about the delimiter is that while reading a fixed chunk of the csv file this chunk might end in the middle of a csv line and therefore the number of delimiters in this line is off.

Working example with whole file:
```python
import csv
csv.Sniffer().sniff("a,b,c\n1,2,3")
```

Problematic example with only part of the file (throws error):
```python
import csv
csv.Sniffer().sniff("a,b,c\n1,2")
```

So I would recommend to use dialect sniffing only (or additionaly?) when the user has not given explicit instructions on the dialect via `CSVKWARGS` and to use `csvfile.readline()` to avoid having a line cut somewhere.

**Comment by gitonthescene** [comment]
I could have sworn I tested exactly this case.  Thanks for opening this issue and the example.  I’ll try to work through it and will post back if I have questions.

**Comment by gitonthescene** [comment]
Actually, did you use the query.zip file referenced in issue #41?  If not, would you mind posting the file you used to reproduce the error and as much detail about how you ran it as you can?

**Comment by gitonthescene** [comment]
@b2m Would you mind testing develop before I push this out in a patch?

**Comment by gitonthescene** [comment]
Awesome.  Thanks.  I’ll try to get this out tomorrow.

**Comment by gitonthescene** [comment]
Fix pushed in [new release](https://github.com/gitonthescene/csv-reconcile/releases/tag/v0.3.2).
