### ISSUE TITLE
localhost:5000/reconcile not displaying properly

### ISSUE THREAD

**Issue by dchoi127** [gitonthescene/csv-reconcile#70]
After executing the following commands:

<img width="791" alt="Screen Shot 2022-05-03 at 2 23 26 PM" src="https://user-images.githubusercontent.com/93415557/166517978-213945ea-fe9a-4974-9c78-0eba3a702dfc.png">

http://127.0.0.1:5000/reconcile displays as 

<img width="1335" alt="Screen Shot 2022-05-03 at 2 24 29 PM" src="https://user-images.githubusercontent.com/93415557/166518117-f43c30e7-9a28-4bb9-8ace-c89236057c3f.png">

The following commands did not result in an error message and all executed successfully. What could the issue be?

I don't believe it's an issue described in #41. To test, I created a config file adding a line 
"CSVENCODING = <csvencoding>" with csvencoding as the encoding for the file and the localhost:5000/reconcile did not change. 

Any suggestions would be greatly appreciated! Thanks!

**Comment by gitonthescene** [comment]
Hi there, I think that's exactly what you should expect when contacting this service directly.  This is what's known as the [service manifest](https://reconciliation-api.github.io/specs/latest/#service-manifest) and is part of the API this service uses to connect with clients.

By far most people will connect to this service using (https://openrefine.org/) open refine but you can connect with any client you want as long as you conform to the API referred to in the [specification](https://reconciliation-api.github.io/specs/latest/).

So I think there's nothing wrong with the server.  If you tell me what you expected and/or trying to do, I might be able to give you some pointers.

Regards

**Comment by dchoi127** [comment]
Sorry! I was thinking that the server was supposed to display something interactive.

I think I'm confused on how to proceed after initializing the database, it seems the instructions halt here. Using my knowledge of the alternate tool, reconcile-csv, would the next step be to run OpenRefine (load my dataset) and add a standard reconciliation service pointing to http://localhost:5000/reconcile and proceed from there?

**Comment by gitonthescene** [comment]
Yes, that’s exactly right.  I believe if you run reconcile-csv and connect to the server the way you did here you’ll get a very similar result because that’s how the API works.  I’ll close this issue now.  Feel free to open another if you’re having trouble.

**Comment by gitonthescene** [comment]
I created a Discussions tab on this project.  If you have more generalized questions please feel free to open one there.
