### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by wetneb** [gitonthescene/csv-reconcile#8]
I am a bit confused by the install instructions in the readme, which currently are (after cloning the repository):

```
$ python -m venv venv                                             # create virtualenv
$ venv/bin/pip install csv-reconcile                              # install package
$ source venv/bin/activate                                        # activate virtual environment
(venv) $ csv-reconcile --init-db sample/reps.tsv item itemLabel   # start the service
(venv) $ deactivate                                               # remove virtual environment
```

It seems to me that this installs csv-reconcile from PyPI (using the latest release) rather than from the code contained in the repository. What are the steps to run the code directly instead?

Generally speaking I expect the following workflow (but perhaps that's old-school!):
```
$ python -m venv venv
$ source venv/bin/activate     # activate the virtualenv before installing anything
$ pip install -r requirements.txt  # install dependencies
$ python setup.py install # install csv-reconcile itself
$ csv-reconcile …
```

**Comment by wetneb** [comment]
I tried doing it via `poetry` as suggested further down in the README, but this failed:

```
python -m venv venv
source venv/bin/activate
pip install poetry
poetry run poe install
```

The last command gave me this error message:
```
  FileNotFoundError

  [Errno 2] No such file or directory: b'/snap/bin/poe'

  at /usr/lib/python3.9/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```

So I suspect poetry needs to be installed globally on my system? But it does not seem to be packaged for Debian. Did I misunderstand something?

**Comment by gitonthescene** [comment]
Yes, generally `poetry` is installed globally per the `poetry` docs linked in the `README`.  You should be able to make it work with a `venv` similar to what you tried, though.  There’s a bootstrapping problem though.  You have to run `poetry install` once and ignore the errors before following the instructions in the `README`.

Though it’s not clear why the `pip` isn’t sufficient for your purposes.  With the `pip` install, you can find the source like so:

``` sh
$ which csv-reconcile
/private/tmp/venv/bin/csv-reconcile
$ python    
Python 3.7.10 (default, Mar 16 2021, 12:40:23) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import csv_reconcile
>>> csv_reconcile
<module 'csv_reconcile' from '/private/tmp/venv/lib/python3.7/site-packages/csv_reconcile/__init__.py'>
>>> 
```
You can edit this file before starting the service.

**Comment by wetneb** [comment]
Ok, I haven't used poetry before but I have to admit I am a bit put off by the convoluted install process. The recommended way to install it seems to be `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`, which is a bit worrisome, no?

Yes I can also edit the installed version in the virtualenv, but it wouldn't really be convenient if I wanted to work on csv-reconcile to submit a PR, would it?

**Comment by gitonthescene** [comment]
Please let me know if you have what you need so I can close this issue.

**Comment by wetneb** [comment]
Sure! I generally assume that when people publish projects on GitHub they are interested in making it easier for others to contribute to those projects, so that's why I felt it made sense to report this (and #9). Personally, I am interested by that sort of feedback (if a part of my tooling is preventing people from contributing, I want to know about it).

But if that is not your intention please do feel free to close this! I will refrain from trying to contribute and from bothering you with those issues any further :)

**Comment by gitonthescene** [comment]
I’m not saying that.  I was trying to focus on getting you running and wasn’t getting any answers back in that regard.  I’m not sure I have yet, but I’ll assume you were able to get it working.

For clarity, the documentation now makes it coear that poetry and poethepoet are _pre-requistes_.  With those installed the instructions are accurate.
