### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by wetneb** [gitonthescene/csv-reconcile#9]
I see there is a test suite already, so perhaps it would be worth running it in a continuous integration service?

As a side effect, this is a good way to document the install process on a stock machine (since you have to script it for the CI). I actually looked for the CI configuration files as a way to solve my install problems (#8).

**Comment by gitonthescene** [comment]
As this is only released manually at the moment, continuous integration isn’t a priority.  There isn’t yet much traffic here.  If interest picks up I’ll look at formalizing processes.

**Comment by gitonthescene** [comment]
Please let me know if you have what you need so I can close this issue.
